name: deploy-container
run-name: "Deploy Container"
on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  test-application:
    name: "Test app"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "Runnign tests"
        uses: 'yuhrao/image-uploader-clj/.github/workflows/tests.yml'

  build-image:
    name: Build Container Image
    needs: test-application

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest version tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Build & Push Latest image
        uses: docker/build-push-action@v3
        with:
          tags: yuhribernardes/image-uploader-clj:latest
          push: true

      - name: Build & Push Versioned image
        uses: docker/build-push-action@v3
        with:
          tags: yuhribernardes/image-uploader-clj:${{ steps.get-latest-tag.outputs.tag }}
          push: true