name: deploy-container
run-name: "Deploy Container"
on:
  push:
    branches: [ main ]
#    tags: [ 'v*.*.*' ]

jobs:
  build-image:
    name: Build Container Image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest version tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Build & Push Latest image
        uses: docker/build-push-action@v3
        with:
          tags: yuhribernardes/image-uploader-clj:latest
          push: true

      - name: Build & Push Versioned image
        uses: docker/build-push-action@v3
        with:
          tags: yuhribernardes/image-uploader-clj:${{ steps.get-latest-tag.outputs.tag }}
          push: true