name: pull-request-checks
run-name: "PUll Request Checks"

on:
  pull_request:
    type: [ opened, synchronize, reopened ]

jobs:
  run-tests:
  runs-on: ubuntu-latest
  steps:
    - name: "Running tests"
      uses: ./.github/workflows/tests.yml